import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect } from 'react';
const PrivacyPolicy = () => {
    useEffect(() => {
        document.title = 'T VARTHA | Privacy Policy';
    }, []);
    return (_jsx("section", { className: "content-page", children: _jsxs("article", { className: "policy-card", children: [_jsx("h1", { children: "Privacy Policy" }), _jsx("p", { children: "This Privacy Policy explains how T VARTHA collects, uses, and protects information when you use our platform." }), _jsxs("p", { children: [_jsx("strong", { children: "Effective date:" }), " March 5, 2026"] }), _jsx("h2", { children: "Information We Collect" }), _jsx("p", { children: "We collect information needed to provide the news posting service." }), _jsxs("ul", { children: [_jsx("li", { children: "Content submitted by users (title, description, and uploaded image)." }), _jsx("li", { children: "Cloudinary-hosted image URLs generated during upload." }), _jsx("li", { children: "System metadata such as created and updated timestamps." })] }), _jsx("h2", { children: "How We Use Information" }), _jsx("p", { children: "Collected information is used only for core platform operations." }), _jsxs("ul", { children: [_jsx("li", { children: "Publish user-submitted news posts." }), _jsx("li", { children: "Maintain chronological ordering of updates." }), _jsx("li", { children: "Improve reliability, security, and user experience." })] }), _jsx("h2", { children: "Data Storage and Security" }), _jsx("p", { children: "News metadata is stored in MongoDB and media files are stored through Cloudinary. We use reasonable administrative and technical safeguards to protect platform data." }), _jsx("h2", { children: "Third-Party Services" }), _jsx("p", { children: "We use trusted third-party services to operate the platform." }), _jsxs("ul", { children: [_jsx("li", { children: "Cloudinary for image hosting and delivery." }), _jsx("li", { children: "MongoDB for persistent data storage." }), _jsx("li", { children: "Potential ad networks for ad delivery (if enabled in future releases)." })] }), _jsx("h2", { children: "Data Retention" }), _jsx("p", { children: "We retain post data while it is needed for platform operation, moderation, and legal compliance." }), _jsx("h2", { children: "Children's Privacy" }), _jsx("p", { children: "T VARTHA is not intended for children under 13. We do not knowingly collect personal information from children." }), _jsx("h2", { children: "User Rights" }), _jsx("p", { children: "Users may contact us regarding access, correction, or deletion requests related to their content." }), _jsx("h2", { children: "Policy Updates" }), _jsx("p", { children: "We may update this Privacy Policy from time to time. Changes will be published on this page with the updated effective date." }), _jsx("h2", { children: "Contact" }), _jsxs("p", { children: ["For privacy-related questions, contact us at", ' ', _jsx("a", { href: "mailto:tvartha2026@gmail.com", children: "tvartha2026@gmail.com" }), "."] })] }) }));
};
export default PrivacyPolicy;
