import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect } from 'react';
const Terms = () => {
    useEffect(() => {
        document.title = 'T VARTHA | Terms and Conditions';
    }, []);
    return (_jsx("section", { className: "content-page", children: _jsxs("article", { className: "policy-card", children: [_jsx("h1", { children: "Terms and Conditions" }), _jsx("p", { children: "Welcome to T VARTHA. By downloading, accessing, or using our application and website, you agree to these Terms and Conditions." }), _jsxs("p", { children: [_jsx("strong", { children: "Effective date:" }), " March 5, 2026"] }), _jsx("h2", { children: "Acceptance of Terms" }), _jsx("p", { children: "By accessing or using T VARTHA, you agree to comply with these Terms and Conditions. If you do not agree, please do not use the platform." }), _jsx("h2", { children: "Nature of the Service" }), _jsx("p", { children: "T VARTHA is a news platform that may present curated or aggregated news information and user-posted updates." }), _jsxs("ul", { children: [_jsx("li", { children: "We may display publicly available content from third-party sources." }), _jsx("li", { children: "Original content rights remain with their respective authors and publishers." }), _jsx("li", { children: "Where available, users can access source links for publisher content." })] }), _jsx("h2", { children: "User Responsibilities" }), _jsxs("ul", { children: [_jsx("li", { children: "Use the application only for lawful purposes." }), _jsx("li", { children: "Do not interfere with normal operation of the application." }), _jsx("li", { children: "Do not attempt to reverse engineer, exploit, or misuse the platform." }), _jsx("li", { children: "Do not publish content that violates rights of others." })] }), _jsx("h2", { children: "Intellectual Property" }), _jsx("p", { children: "Trademarks, logos, and third-party news content shown in T VARTHA belong to their respective owners. T VARTHA does not claim ownership over third-party publisher content." }), _jsx("h2", { children: "Third-Party Links" }), _jsx("p", { children: "The platform may include links to external publisher websites. We do not control and are not responsible for third-party content, terms, or privacy practices." }), _jsx("h2", { children: "Advertisements" }), _jsx("p", { children: "T VARTHA may display ads through third-party ad networks. These services may process device or usage information according to their own policies." }), _jsx("h2", { children: "Limitation of Liability" }), _jsx("p", { children: "T VARTHA is provided on an \"as is\" basis without warranties of any kind. We do not guarantee the completeness, accuracy, or reliability of third-party news content." }), _jsx("h2", { children: "Changes to Terms" }), _jsx("p", { children: "We may update these Terms from time to time. Updates will be published on this page with a revised effective date." }), _jsx("h2", { children: "Contact Us" }), _jsxs("p", { children: ["If you have questions regarding these Terms and Conditions, contact us at", ' ', _jsx("a", { href: "mailto:tvartha2026@gmail.com", children: "tvartha2026@gmail.com" }), "."] })] }) }));
};
export default Terms;
